services:
  - type: static
    name: spa_alegentai
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    domains:
      - alegentai.com
      - www.alegentai.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
